"""Static HTML report generator.

Deliberately boring technology: one self-contained HTML file per report, no
server, no JavaScript framework, no build step. It renders a run summary
(metrics, failures, per-case table) and, when provided, a baseline-vs-candidate
comparison. Reports are artifacts to attach to a PR or a release note, not an
application.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

_COLOR = {
    "improved": "#0a7d33",
    "regressed": "#b3261e",
    "neutral": "#555555",
}


def _esc(value: Any) -> str:
    return html.escape(str(value))


def _fmt(value: Any) -> str:
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:.4f}".rstrip("0").rstrip(".") or "0"
    return str(value)


def _metric_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "<p>No metrics.</p>"
    header = (
        "<tr><th>metric</th><th>direction</th><th>baseline</th>"
        "<th>candidate</th><th>delta</th><th>verdict</th></tr>"
    )
    body = []
    for row in rows:
        color = _COLOR.get(row["verdict"], "#555")
        body.append(
            f"<tr><td>{_esc(row['metric'])}</td><td>{_esc(row['direction'])}-better</td>"
            f"<td>{_fmt(row['baseline'])}</td><td>{_fmt(row['candidate'])}</td>"
            f"<td>{_fmt(row['delta'])}</td>"
            f"<td style='color:{color};font-weight:600'>{_esc(row['verdict'])}</td></tr>"
        )
    return f"<table>{header}{''.join(body)}</table>"


def _case_table(per_case: list[dict[str, Any]], include_answer: bool = True) -> str:
    if not per_case:
        return "<p>No cases.</p>"
    cols = ["case_id", "keyword_recall", "citation_coverage", "groundedness",
            "retrieval_recall", "latency_ms", "total_tokens", "failure"]
    cols = [c for c in cols if any(c in row for row in per_case)]
    header = "".join(f"<th>{_esc(c)}</th>" for c in cols)
    body = []
    for row in per_case:
        cells = []
        for c in cols:
            v = row.get(c)
            style = ""
            if c == "failure" and v:
                style = "style='color:#b3261e'"
            cells.append(f"<td {style}>{_fmt(v)}</td>")
        body.append(f"<tr>{''.join(cells)}</tr>")
    table = f"<table><tr>{header}</tr>{''.join(body)}</table>"
    if include_answer:
        details = []
        for row in per_case:
            answer = row.get("answer") or ""
            failure = row.get("failure") or ""
            details.append(
                f"<details><summary>{_esc(row['case_id'])}"
                f"{' - ' + _esc(failure) if failure else ''}</summary>"
                f"<pre>{_esc(answer[:500])}</pre></details>"
            )
        return table + "".join(details)
    return table


_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AIRE report - {title}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem auto;
         max-width: 60rem; color: #1a1a1a; }}
  h1 {{ font-size: 1.4rem; }} h2 {{ font-size: 1.1rem; margin-top: 2rem; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
  th, td {{ border-bottom: 1px solid #ddd; padding: 6px 8px; text-align: left; }}
  th {{ background: #f6f6f6; }}
  .summary {{ background: #f6f6f6; padding: 1rem; border-radius: 6px; }}
  .verdict-regressions-detected {{ color: #b3261e; font-weight: 700; }}
  .verdict-no-regressions-detected {{ color: #0a7d33; font-weight: 700; }}
  details {{ margin: 4px 0; font-size: 0.85rem; }}
  pre {{ white-space: pre-wrap; background: #fafafa; padding: 8px; border-radius: 4px; }}
  .meta {{ color: #555; font-size: 0.85rem; }}
</style>
</head>
<body>
{body}
<p class="meta">Generated by AIRE - static report, no server required.</p>
</body>
</html>
"""


def render_run_report(
    run_dir: str | Path,
    eval_results: dict[str, Any],
    out_path: str | Path,
    title: str | None = None,
) -> Path:
    """Render a single-run report page."""
    run_dir = Path(run_dir)
    manifest: dict[str, Any] = {}
    mpath = run_dir / "manifest.json"
    if mpath.exists():
        manifest = json.loads(mpath.read_text(encoding="utf-8"))
    title = title or manifest.get("name", run_dir.name)
    agg = eval_results.get("aggregates", {})
    chips = ", ".join(f"{_esc(k.removeprefix('mean_'))}: {_fmt(v)}" for k, v in agg.items() if k != "failure_counts")
    failures = agg.get("failure_counts", {})
    failure_str = ", ".join(f"{_esc(k)}: {v}" for k, v in failures.items()) or "none"

    body = f"""
<h1>AIRE run report: {_esc(title)}</h1>
<div class="summary">
  <b>Aggregate metrics</b> - {chips or "none"}<br>
  <b>Failures</b> - {failure_str}<br>
  <b>Cases</b> - {_fmt(agg.get('n_cases', len(eval_results.get('per_case', []))))}
</div>
<h2>Per-case results</h2>
{_case_table(eval_results.get('per_case', []))}
"""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_PAGE.format(title=_esc(title), body=body), encoding="utf-8")
    return out


def render_comparison_report(
    comparison: dict[str, Any],
    eval_results_baseline: dict[str, Any],
    eval_results_candidate: dict[str, Any],
    out_path: str | Path,
    title: str = "A vs B",
) -> Path:
    """Render a baseline-vs-candidate regression report page."""
    verdict = comparison["summary"]["verdict"]
    body = f"""
<h1>AIRE comparison: {_esc(title)}</h1>
<div class="summary">
  <span class="verdict-{_esc(verdict.replace(' ', '-'))}">{_esc(verdict)}</span><br>
  improved: {comparison['summary']['n_improved']} -
  regressed: {comparison['summary']['n_regressed']} -
  neutral: {comparison['summary']['n_neutral']}<br>
  <b>Failure count deltas</b>: {_esc(comparison.get('failure_count_deltas') or 'none')}
</div>
<h2>Metric comparison</h2>
{_metric_table(comparison.get('metrics', []))}
<h2>Baseline cases</h2>
{_case_table(eval_results_baseline.get('per_case', []), include_answer=False)}
<h2>Candidate cases</h2>
{_case_table(eval_results_candidate.get('per_case', []), include_answer=False)}
"""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_PAGE.format(title=_esc(title), body=body), encoding="utf-8")
    return out
