#!/usr/bin/env python
"""Build demo-site/data.js from the committed results/ JSONs.

    python demo-site/build.py        # from the repo root

Renders exactly the committed evaluations: deterministic v1/v2/v3 runs (with
traces joined per case) and the recorded live-LLM run, plus the committed
regression comparisons. Nothing is hand-typed.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_version(name: str) -> dict:
    d = load(RESULTS / name / "eval_results.json")
    traces = {}
    tpath = RESULTS / name / "traces.jsonl"
    if tpath.exists():
        for line in tpath.read_text(encoding="utf-8").splitlines():
            if line.strip():
                t = json.loads(line)
                traces[t["case_id"]] = {
                    "retrieved_doc_ids": t.get("retrieved_doc_ids", []),
                    "spans": [
                        {"kind": s.get("kind"), "name": s.get("name"),
                         "latency_ms": round(s.get("latency_ms", 0), 3)}
                        for s in t.get("spans", [])
                    ],
                    "usage": t.get("usage", {}),
                    "error": t.get("error"),
                }
    for row in d.get("per_case", []):
        row["trace"] = traces.get(row.get("case_id"), {})
    return d


def slim_comparison(name: str) -> dict:
    c = load(RESULTS / name)
    return {
        "summary": c["summary"],
        "metrics": c["metrics"],
        "failure_count_deltas": c.get("failure_count_deltas", {}),
    }


llm = load(RESULTS / "llm_eval_results.json")
for row in llm.get("per_case", []):
    row["trace"] = {}  # live-LLM run has no committed traces.jsonl in results/
llm_slim = {
    "aggregates": llm["aggregates"],
    "per_case": llm["per_case"],
    "generator": llm.get("generator"),
    "mode": llm.get("mode"),
    "totals": {
        "prompt_tokens": llm.get("total_api_prompt_tokens"),
        "completion_tokens": llm.get("total_api_completion_tokens"),
        "api_calls": llm.get("total_api_calls"),
    },
}

data = {
    "versions": {
        "v1_baseline": load_version("v1_baseline"),
        "v2_improved": load_version("v2_improved"),
        "v3_fluent_regression": load_version("v3_fluent_regression"),
    },
    "llm": llm_slim,
    "comparisons": {
        "v2_vs_v1": slim_comparison("v2_improved_vs_v1_baseline.json"),
        "v3_vs_v1": slim_comparison("v3_fluent_regression_vs_v1_baseline.json"),
        "llm_vs_v2": slim_comparison("llm_vs_deterministic.json"),
    },
}

out = Path(__file__).resolve().parent / "data.js"
out.write_text(
    "// Generated by demo-site/build.py from committed results/ - do not hand-edit.\n"
    "window.DATA = " + json.dumps(data, indent=1) + ";\n",
    encoding="utf-8",
)
print(f"wrote {out} ({out.stat().st_size} bytes)")
